<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>微信车站通测试报告!</title>
    <meta name="generator" content="BSTestRunner 0.8.4"/>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
    
<style type="text/css" media="screen">

/* -- css div popup ------------------------------------------------------------------------ */
.popup_window {
    display: none;
    position: relative;
    left: 0px;
    top: 0px;
    /*border: solid #627173 1px; */
    padding: 10px;
    background-color: #99CCFF;
    font-family: "Lucida Console", "Courier New", Courier, monospace;
    text-align: left;
    font-size: 10pt;
    width: 500px;
}

/* -- report ------------------------------------------------------------------------ */

#show_detail_line .label {
    font-size: 85%;
    cursor: pointer;
}

#show_detail_line {
    margin: 2em auto 1em auto;
}

#total_row  { font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }

</style>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<body>
<script language="javascript" type="text/javascript"><!--
output_list = Array();

/* level - 0:Summary; 1:Failed; 2:All */
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level < 1) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level > 1) {
                tr.className = '';
            }
            else {
                tr.className = 'hiddenRow';
            }
        }
    }
}


function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        tid0 = 't' + cid.substr(1) + '.' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        if (toHide) {
            document.getElementById('div_'+tid).style.display = 'none'
            document.getElementById(tid).className = 'hiddenRow';
        }
        else {
            document.getElementById(tid).className = '';
        }
    }
}


function showTestDetail(div_id){
    var details_div = document.getElementById(div_id)
    var displayState = details_div.style.display
    // alert(displayState)
    if (displayState != 'block' ) {
        displayState = 'block'
        details_div.style.display = 'block'
    }
    else {
        details_div.style.display = 'none'
    }
}


function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}

/* obsoleted by detail in <div>
function showOutput(id, name) {
    var w = window.open("", //url
                    name,
                    "resizable,scrollbars,status,width=800,height=450");
    d = w.document;
    d.write("<pre>");
    d.write(html_escape(output_list[id]));
    d.write("\n");
    d.write("<a href='javascript:window.close()'>close</a>\n");
    d.write("</pre>\n");
    d.close();
}
*/
--></script>

<div class="container">
    <div class='heading'>
<h1>微信车站通测试报告!</h1>
<p><strong>Start Time:</strong> 2019-09-17 11:37:06</p>
<p><strong>Duration:</strong> 0:00:32.646828</p>
<p><strong>Status:</strong> <span class="text text-success">Pass <strong>1</strong></span> <span class="text text-warning">Error <strong>74</strong></span></p>

<p class='description'>测试个人中心模块!</p>
</div>


    
<p id='show_detail_line'>
<span class="label label-primary" onclick="showCase(0)">Summary</span>
<span class="label label-danger" onclick="showCase(1)">Failed</span>
<span class="label label-default" onclick="showCase(2)">All</span>
</p>
<table id='result_table' class="table">
    <thead>
        <tr id='header_row'>
            <th>Test Group/Test case</td>
            <th>Count</td>
            <th>Pass</td>
            <th>Fail</td>
            <th>Error</td>
            <th>View</td>
        </tr>
    </thead>
    <tbody>
        
<tr class='text text-warning'>
    <td>test_1_首页.tc_首页</td>
    <td>33</td>
    <td>1</td>
    <td>0</td>
    <td>32</td>
    <td><a class="btn btn-xs btn-primary"href="javascript:showClassDetail('c1',33)">Detail</a></td>
</tr>

<tr id='pt1.1' class='hiddenRow'>
    <td class='text text-success'><div class='testcase'>test_002_点击切换站点toast切换站点_武昌站</div></td>
    <td colspan='5' align='center'>pass</td>
</tr>

<tr id='ft1.2' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_005_站点切换页面调转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.2')" >
        error</a>

    <div id='div_ft1.2' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.2').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.2: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.3' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_007_首页天气页面跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.3')" >
        error</a>

    <div id='div_ft1.3' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.3').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.3: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.4' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_010_banner车站流量跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.4')" >
        error</a>

    <div id='div_ft1.4' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.4').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.4: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.5' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_011_车站流量旅客流量字段检查</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.5')" >
        error</a>

    <div id='div_ft1.5' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.5').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.5: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.6' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_012_车站流量车次流量字段检查</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.6')" >
        error</a>

    <div id='div_ft1.6' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.6').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.6: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.7' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_013_车站流量到达大屏字段检查</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.7')" >
        error</a>

    <div id='div_ft1.7' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.7').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.7: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.8' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_014_车站流量候车大屏字段检查</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.8')" >
        error</a>

    <div id='div_ft1.8' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.8').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.8: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.9' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_015_车站流量车站大屏跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.9')" >
        error</a>

    <div id='div_ft1.9' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.9').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.9: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.10' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_017_车站流量正晚点查询跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.10')" >
        error</a>

    <div id='div_ft1.10' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.10').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.10: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.11' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_018_车站流量行李托运跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.11')" >
        error</a>

    <div id='div_ft1.11' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.11').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.11: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.12' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_019_车站流量车站地图跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.12')" >
        error</a>

    <div id='div_ft1.12' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.12').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.12: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.13' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_020_切换到测试站点_浠水站</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.13')" >
        error</a>

    <div id='div_ft1.13' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.13').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.13: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.14' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_027_更多服务屏幕跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.14')" >
        error</a>

    <div id='div_ft1.14' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.14').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.14: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.15' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_028_公告详情页面跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.15')" >
        error</a>

    <div id='div_ft1.15' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.15').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.15: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.16' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_029_更多资讯页面跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.16')" >
        error</a>

    <div id='div_ft1.16' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.16').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.16: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.17' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_030_车次号为空toast提示</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.17')" >
        error</a>

    <div id='div_ft1.17' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.17').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.17: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.18' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_031_车次查询摄像头调用</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.18')" >
        error</a>

    <div id='div_ft1.18' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.18').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.18: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.19' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_032_站站查询标签页切换</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.19')" >
        error</a>

    <div id='div_ft1.19' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.19').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.19: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.20' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_033_车次查询标签页切换</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.20')" >
        error</a>

    <div id='div_ft1.20' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.20').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.20: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.21' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_034_时刻查询选择日期页面跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.21')" >
        error</a>

    <div id='div_ft1.21' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.21').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.21: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.22' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_037_时刻查询_站站查询结果跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.22')" >
        error</a>

    <div id='div_ft1.22' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.22').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.22: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.23' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_045_首页_到达切换</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.23')" >
        error</a>

    <div id='div_ft1.23' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.23').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.23: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.24' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_048_首页_候车切换</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.24')" >
        error</a>

    <div id='div_ft1.24' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.24').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.24: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.25' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_050_车站大屏页面跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.25')" >
        error</a>

    <div id='div_ft1.25' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.25').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.25: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.26' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_060_查看全部跳转站内商业</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.26')" >
        error</a>

    <div id='div_ft1.26' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.26').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.26: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.27' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_065_进站后按钮切换</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.27')" >
        error</a>

    <div id='div_ft1.27' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.27').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.27: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.28' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_068_进站前按钮切换</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.28')" >
        error</a>

    <div id='div_ft1.28' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.28').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.28: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.29' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_075_功能待完善提示</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.29')" >
        error</a>

    <div id='div_ft1.29' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.29').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.29: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.30' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_100_首页军人优先跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.30')" >
        error</a>

    <div id='div_ft1.30' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.30').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.30: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.31' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_105_首页常见问题跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.31')" >
        error</a>

    <div id='div_ft1.31' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.31').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.31: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.32' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_110_首页服务评价跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.32')" >
        error</a>

    <div id='div_ft1.32' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.32').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.32: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.33' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_115_首页关于我们跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.33')" >
        error</a>

    <div id='div_ft1.33' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.33').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.33: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_1_首页.py", line 24, in setUp
    dr.act_下滑(3)
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 196, in act_下滑
    l = self.get_screenSize()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 114, in get_screenSize
    x = self.get_窗口尺寸()['width']
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 169, in get_窗口尺寸
    return self.driver.get_window_size()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1108, in get_window_size
    size = self.get_window_rect()
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1165, in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='text text-warning'>
    <td>test_20_行程.tc_行程</td>
    <td>2</td>
    <td>0</td>
    <td>0</td>
    <td>2</td>
    <td><a class="btn btn-xs btn-primary"href="javascript:showClassDetail('c2',2)">Detail</a></td>
</tr>

<tr id='ft2.1' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_1_添加行程弹出选择框</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft2.1')" >
        error</a>

    <div id='div_ft2.1' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft2.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft2.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_20_行程.py", line 8, in setUp
    dr.click_行程()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 73, in click_行程
    self.click_点击(self.btn_行程, "btn_行程")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft2.2' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_2_手动添加行程跳转到关注行程页</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft2.2')" >
        error</a>

    <div id='div_ft2.2' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft2.2').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft2.2: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_20_行程.py", line 8, in setUp
    dr.click_行程()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 73, in click_行程
    self.click_点击(self.btn_行程, "btn_行程")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='text text-warning'>
    <td>test_30_个人中心.tc_个人中心</td>
    <td>7</td>
    <td>0</td>
    <td>0</td>
    <td>7</td>
    <td><a class="btn btn-xs btn-primary"href="javascript:showClassDetail('c3',7)">Detail</a></td>
</tr>

<tr id='ft3.1' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_202_个人中心跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.1')" >
        error</a>

    <div id='div_ft3.1' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_30_个人中心.py", line 12, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft3.2' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_203_我的资料跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.2')" >
        error</a>

    <div id='div_ft3.2' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.2').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.2: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_30_个人中心.py", line 12, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft3.3' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_204_点击积分商城给提示</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.3')" >
        error</a>

    <div id='div_ft3.3' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.3').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.3: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_30_个人中心.py", line 12, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft3.4' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_205_点击优惠券给提示</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.4')" >
        error</a>

    <div id='div_ft3.4' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.4').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.4: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_30_个人中心.py", line 12, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft3.5' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_206_我的12306跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.5')" >
        error</a>

    <div id='div_ft3.5' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.5').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.5: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_30_个人中心.py", line 12, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft3.6' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_207_我的行程跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.6')" >
        error</a>

    <div id='div_ft3.6' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.6').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.6: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_30_个人中心.py", line 12, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft3.7' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_208_意见反馈跳转</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.7')" >
        error</a>

    <div id='div_ft3.7' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.7').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.7: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_30_个人中心.py", line 12, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='text text-warning'>
    <td>test_35_意见反馈.tc_意见反馈</td>
    <td>4</td>
    <td>0</td>
    <td>0</td>
    <td>4</td>
    <td><a class="btn btn-xs btn-primary"href="javascript:showClassDetail('c4',4)">Detail</a></td>
</tr>

<tr id='ft4.1' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_202_详细描述和联系方式都为空给出提示</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.1')" >
        error</a>

    <div id='div_ft4.1' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_35_意见反馈.py", line 10, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft4.2' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_203_仅详细描述为空给出提示</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.2')" >
        error</a>

    <div id='div_ft4.2' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.2').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.2: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_35_意见反馈.py", line 10, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft4.3' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_204_联系方式都为空给出提示</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.3')" >
        error</a>

    <div id='div_ft4.3' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.3').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.3: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_35_意见反馈.py", line 10, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft4.4' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_205_意见反馈主流程全部填写</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.4')" >
        error</a>

    <div id='div_ft4.4' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.4').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.4: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_35_意见反馈.py", line 10, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='text text-warning'>
    <td>test_40_我的资料.tc_我的资料</td>
    <td>4</td>
    <td>0</td>
    <td>0</td>
    <td>4</td>
    <td><a class="btn btn-xs btn-primary"href="javascript:showClassDetail('c5',4)">Detail</a></td>
</tr>

<tr id='ft5.1' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_102_是否有城市选择控件弹出</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.1')" >
        error</a>

    <div id='div_ft5.1' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft5.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft5.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_40_我的资料.py", line 13, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft5.2' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_103_是否有日期选择控件弹出</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.2')" >
        error</a>

    <div id='div_ft5.2' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft5.2').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft5.2: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_40_我的资料.py", line 13, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft5.3' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_104_确认修改出生日期</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.3')" >
        error</a>

    <div id='div_ft5.3' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft5.3').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft5.3: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_40_我的资料.py", line 13, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft5.4' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_105_取消修改出生日期</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.4')" >
        error</a>

    <div id='div_ft5.4' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft5.4').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft5.4: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_40_我的资料.py", line 13, in setUp
    dr.click_我的按钮()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 79, in click_我的按钮
    self.click_点击(self.btn_我的, "btn_我的")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='text text-warning'>
    <td>test_45_车站大屏.tc_车站大屏详情</td>
    <td>2</td>
    <td>0</td>
    <td>0</td>
    <td>2</td>
    <td><a class="btn btn-xs btn-primary"href="javascript:showClassDetail('c6',2)">Detail</a></td>
</tr>

<tr id='ft6.1' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_001_车站大屏候车字段检查</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.1')" >
        error</a>

    <div id='div_ft6.1' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft6.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft6.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_45_车站大屏.py", line 9, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.2' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_002_车站大屏到达字段检查</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.2')" >
        error</a>

    <div id='div_ft6.2' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft6.2').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft6.2: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_45_车站大屏.py", line 9, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='text text-warning'>
    <td>test_50_车次详情.tc_车次详情</td>
    <td>3</td>
    <td>0</td>
    <td>0</td>
    <td>3</td>
    <td><a class="btn btn-xs btn-primary"href="javascript:showClassDetail('c7',3)">Detail</a></td>
</tr>

<tr id='ft7.1' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_500_首页车次号搜索绑定行程</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.1')" >
        error</a>

    <div id='div_ft7.1' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft7.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft7.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_50_车次详情.py", line 12, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.2' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_501_行程车次号搜索绑定行程</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.2')" >
        error</a>

    <div id='div_ft7.2' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft7.2').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft7.2: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_50_车次详情.py", line 12, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.3' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_502_首页删除行程</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.3')" >
        error</a>

    <div id='div_ft7.3' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft7.3').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft7.3: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_50_车次详情.py", line 12, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='text text-warning'>
    <td>test_5_站内商业.tc_站内商业</td>
    <td>12</td>
    <td>0</td>
    <td>0</td>
    <td>12</td>
    <td><a class="btn btn-xs btn-primary"href="javascript:showClassDetail('c8',12)">Detail</a></td>
</tr>

<tr id='ft8.1' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_301_所有楼层展开</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.1')" >
        error</a>

    <div id='div_ft8.1' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.2' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_303_全部分类展开</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.2')" >
        error</a>

    <div id='div_ft8.2' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.2').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.2: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.3' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_305_全部分类展开</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.3')" >
        error</a>

    <div id='div_ft8.3' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.3').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.3: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.4' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_307_进站前后展开</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.4')" >
        error</a>

    <div id='div_ft8.4' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.4').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.4: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.5' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_309_跳转店铺详情</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.5')" >
        error</a>

    <div id='div_ft8.5' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.5').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.5: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.6' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_310_单条件筛选_所有楼层_一层</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.6')" >
        error</a>

    <div id='div_ft8.6' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.6').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.6: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.7' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_311_单条件筛选_所有楼层_负一层_无结果</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.7')" >
        error</a>

    <div id='div_ft8.7' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.7').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.7: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.8' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_312_单条件筛选_所有分类_美食_无结果</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.8')" >
        error</a>

    <div id='div_ft8.8' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.8').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.8: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.9' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_313_单条件筛选_所有分类_超市</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.9')" >
        error</a>

    <div id='div_ft8.9' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.9').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.9: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.10' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_314_单条件筛选_进站前后_进站前</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.10')" >
        error</a>

    <div id='div_ft8.10' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.10').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.10: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.11' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_315_单条件筛选_进站前后_进站后</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.11')" >
        error</a>

    <div id='div_ft8.11' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.11').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.11: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.12' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_399_标记归零</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.12')" >
        error</a>

    <div id='div_ft8.12' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.12').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.12: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_5_站内商业.py", line 17, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='text text-warning'>
    <td>test_6_填写评论.tc_填写评论</td>
    <td>8</td>
    <td>0</td>
    <td>0</td>
    <td>8</td>
    <td><a class="btn btn-xs btn-primary"href="javascript:showClassDetail('c9',8)">Detail</a></td>
</tr>

<tr id='ft9.1' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_001_全部为空提示</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.1')" >
        error</a>

    <div id='div_ft9.1' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft9.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft9.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_6_填写评论.py", line 14, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft9.2' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_002_评分为空提示</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.2')" >
        error</a>

    <div id='div_ft9.2' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft9.2').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft9.2: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_6_填写评论.py", line 14, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft9.3' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_003_评论为空提示</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.3')" >
        error</a>

    <div id='div_ft9.3' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft9.3').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft9.3: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_6_填写评论.py", line 14, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft9.4' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_004_主流程全部填写</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.4')" >
        error</a>

    <div id='div_ft9.4' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft9.4').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft9.4: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_6_填写评论.py", line 14, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft9.5' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_005_主流程不上传图片</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.5')" >
        error</a>

    <div id='div_ft9.5' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft9.5').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft9.5: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_6_填写评论.py", line 14, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft9.6' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_006_主流程不上传图片不匿名</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.6')" >
        error</a>

    <div id='div_ft9.6' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft9.6').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft9.6: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_6_填写评论.py", line 14, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft9.7' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_007_主流程不匿名</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.7')" >
        error</a>

    <div id='div_ft9.7' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft9.7').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft9.7: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_6_填写评论.py", line 14, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft9.8' class='text text-success'>
    <td class='text text-warning'><div class='testcase'>test_008_评论少于5个字</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link btn btn-xs btn-default" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.8')" >
        error</a>

    <div id='div_ft9.8' class="popup_window">
        <div style='text-align: right;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft9.8').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft9.8: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\station_mapp\testCase\test_6_填写评论.py", line 14, in setUp
    dr.click_首页()
  File "C:\Users\Administrator\Desktop\station_mapp\common\common.py", line 69, in click_首页
    self.click_点击(self.btn_首页, "btn_首页")
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in click_点击
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Administrator\Desktop\station_mapp\baseView\baseView.py", line 38, in &lt;lambda&gt;
    WebDriverWait(self.driver, 12).until(lambda x: x.find_element_by_android_uiautomator(loc))
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 366, in find_element_by_android_uiautomator
    return self.find_element(by=MobileBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "F:\python_1\lib\site-packages\appium\webdriver\webdriver.py", line 258, in find_element
    'value': value})['value']
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "F:\python_1\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "F:\python_1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET



        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    </tbody>
    <tfoot>
        <tr id='total_row'>
            <td>Total</td>
            <td>75</td>
            <td class="text text-success">1</td>
            <td class="text text-danger">0</td>
            <td class="text text-warning">74</td>
            <td>&nbsp;</td>
        </tr>
    </tfoot>
</table>

    <div id='ending'>&nbsp;</div>
</div>

</body>
</html>
